resolver: lts-14.14

extra-deps:
- git: https://github.com/serokell/lootbox.git
  commit: 2a17f458a4cfe8ad3e34674318112621bd31bd7e
  subdirs:
    - code/base
    - code/prelude

# not in lts:
- aeson-options-0.1.0
- github-0.23
- github-webhooks-0.11.0
- servant-github-webhook-0.4.2.0

# required by github:
- binary-instances-1

# lts version is too old:
- shelly-1.9.0
